services:
  mjml:
    build:
      context: .
      dockerfile_inline: |
        FROM alpine:latest
        WORKDIR /mjml
        RUN apk update; apk add npm bash
        RUN npm init -y && npm install mjml
        ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/mjml/node_modules/.bin
    volumes:
      - type: bind
        source: .
        target: /src
    working_dir: /src
  
  dev:
    build:
      context: .
      dockerfile_inline: |
        FROM ruby:3.3-bookworm
        RUN apt update
        RUN useradd -m -u 1000 ${USER}
        USER ${USER}
    ports:
      - "4000:4000"
    working_dir: /src
    command: /bin/sh -c "bundle install && (cd docs; bundle exec jekyll serve -H 0.0.0.0)"
    volumes:
      - type: bind
        source: .
        target: /src
      - type: volume
        source: bundle_cache
        target: /home/${USER}/.bundle
      - type: bind
        source: ../eef-jekyll-theme
        target: /eef-jekyll-theme
        
  fix-vol:
    image: alpine:latest
    user: root
    command: chown 1000 /bundle
    volumes:
      - type: volume
        source: bundle_cache
        target: /bundle
            
volumes:
  bundle_cache:
