#!/bin/sh

o2="$2/${1##*/}"
output="${o2%.mjml}.html"

id=$(docker compose run --rm -d --user $(id -u) mjml mjml --config.allowIncludes --watch $1 -o $output)

trap "echo Stopping; docker stop $id" INT EXIT
docker logs -f $id
