#!/bin/sh

inkscape="/Applications/Inkscape.app/Contents/MacOS/inkscape"

if [ ! -x "$inkscape" ]; then
    echo "works on macos with inkscape. install"
    exit 1
fi

input=$1
if [ ! -f "$input" ]; then
    echo "$input missing"
    exit
fi

output1=${input##*/}
output="${output1%.svg}.png"

$inkscape \
    --export-filename=$output \
    --export-type=png \
    --export-area-page \
    --export-width 1200 \
    $input
